# Generated by Django 4.2.7 on 2024-05-31 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
